stages:
  
  preprocess:
    cmd: python code/1_preprocess.py
    deps:
    - code/1_preprocess.py
    outs:
    - data/processed/

  build_tensordataset:
    cmd: python code/2_build_tensordataset.py
    deps:
    - code/2_build_tensordataset.py
    - data/processed/
    outs:
    - data/tensordataset/
    - brick/selfies_property_val_tokenizer/

  train:
    cmd: python code/3_train_multitask_transformer.py
    deps:
    - code/3_train_multitask_transformer.py
    - data/processed/
    - data/tensordataset/
    - brick/selfies_property_val_tokenizer/
    outs:
    - brick/moe

  evaluate:
    cmd: python code/5_1_eval_multi_properties.py
    deps:
    - code/5_1_eval_multi_properties.py
    - brick/moe
    - brick/selfies_property_val_tokenizer/
    - data/tensordataset/multitask_tensors/hld
    outs:
    - data/metrics/multitask_predictions.csv
    - data/metrics/multitask_metrics.csv
  
  sqlite:
    cmd: python code/6_build_sqlite.py
    deps:
    - code/6_build_sqlite.py
    outs:
    - brick/cvae.sqlite