stages:
  
  # requirements:
  #   cmd: bash code/0_Requirements.sh
  #   deps:
  #   - requirements.txt
  #   outs:
  #   - .dvc/cache

  preprocess:
    cmd: python code/1_preprocess.py
    deps:
    - code/1_preprocess.py
    outs:
    - data/processed/

  build_tensordataset:
    cmd: python code/2_build_tensordataset.py
    deps:
    - code/2_build_tensordataset.py
    - data/processed/
    outs:
    - data/tensordataset/
    - brick/selfies_property_val_tokenizer/

  train:
    cmd: python code/3_train_multitask_transformer.py
    deps:
    - code/3_train_multitask_transformer.py
    - data/processed/
    - data/tensordataset/
    - brick/selfies_property_val_tokenizer/
    outs:
    - brick/mtransform2

  # test:
  #   cmd: python code/4_Test.py
  #   deps:
  #   - code/4_Test.py
  #   - data/processed
  #   - models/train
  #   outs:
  #   - metrics/test

  # inference:
  #   cmd: python code/5_Inference.py
  #   deps:
  #   - code/5_Inference.py
  #   - data/processed
  #   - models/train
  #   outs:
  #   - metrics/inference
  
  sqlite:
    cmd: python code/6_build_sqlite.py
    deps:
    - code/6_build_sqlite.py
    outs:
    - brick/cvae.sqlite