stages:
  
  preprocess:
    cmd: PYTHONPATH=./ python code/1_preprocess.py
    deps:
    - code/1_preprocess.py
    outs:
    - cache/preprocess/

  preprocess_tokenizer:
    cmd: PYTHONPATH=./ python code/1_2_preprocess_tokenizer.py
    deps:
    - code/1_2_preprocess_tokenizer.py
    - cache/preprocess/
    outs:
    - cache/preprocess_tokenizer/

  build_tensordataset:
    cmd: python code/2_build_tensordataset.py
    deps:
    - code/2_build_tensordataset.py
    - cache/preprocess/
    outs:
    - data/tensordataset/
    - brick/selfies_property_val_tokenizer/
  
  pack_tensordataset:
    cmd: PYTHONPATH=./ python code/3_0_pack_multitask_tensors.py
    deps:
    - cache/build_multitask_tensors/
    outs:
    - cache/pack_multitask_tensors/

  train:
    cmd: python code/3_train_multitask_transformer.py
    deps:
    - code/3_train_multitask_transformer.py
    - cache/preprocess/
    - data/tensordataset/
    - brick/selfies_property_val_tokenizer/
    outs:
    - brick/moe

  # evaluate:
  #   cmd: python code/5_1_eval_multi_properties.py
  #   deps:
  #     - code/5_1_eval_multi_properties.py
  #     - brick/moe
  #     - data/tensordataset/multitask_tensors/hld
  #   outs:
  #     - data/metrics/temp
  #     - data/metrics/multitask_predictions.parquet
  #     - data/metrics/multitask_metrics.parquet

  sqlite:
    cmd: python code/6_build_sqlite.py
    deps:
      - code/6_build_sqlite.py
      - brick/selfies_property_val_tokenizer
      - cache/preprocess/activities.parquet
    outs:
      - brick/cvae.sqlite
  
  evaluate_benchmarks:
    cmd: python code/7.1_2_property_benchmarks_parallel.py
    deps:
      - code/7.1_2_property_benchmarks_parallel.py
      - brick/moe
      - data/tensordataset/multitask_tensors/hld
    outs:
      - data/metrics/temp
      - data/metrics/multitask_predictions.parquet
      - data/metrics/multitask_metrics.parquet