latentDim: 512

download:
  outFolder: data/raw/

preprocessing:
  rawDataPath: data/raw/RawChemHarmony.csv
  outDataFolder: data/processed/

training:
  metricsOutPath: metrics/train/
  processedData: data/processed/
  outModelFolder: models/train/
  epochs: 100

testing:
  modelFolder: models/train/
  processedData: data/processed/
  metricsOutPath: metrics/test/

inference:
  modelFolder: models/train/
  processedData: data/processed/
  metricsOutPath: metrics/inference/
