latentDim: 512

preprocessing:
  rawDataPath: data/raw/RawChemHarmony.csv
  outDataFolder: data/processed/

training:
  metricsOutPath: metrics/
  processedData: data/processed/
  outModelFolder: models/train/
  epochs: 100